#!/usr/bin/env bash
set -eu

[ "$#" -lt 2 ] && echo "Usage: $0 [options] filename" >&2 && exit 1

args=("${@:1:$#-1}") # bash array magic slicing everything but the last argument
file=${!#}
tmpfile=$(mktemp --suffix="$file.cut")
zeek-cut "${args[@]}" <"$file" >"$tmpfile" && mv "$tmpfile" "$file"
exec btest-diff "$file"
