#! /usr/bin/env bash
#
# Default canonifier used with the trace-based tests in testing/external/*.

`dirname $0`/diff-remove-timestamps \
    | `dirname $0`/diff-remove-uids \
    | `dirname $0`/diff-remove-mime-types \
    | `dirname $0`/diff-remove-x509-names \
    | `dirname $0`/diff-canon-notice-policy \
    | `dirname $0`/diff-sort

