#! /usr/bin/env bash
#
# Replace absolute paths with the basename.

if [ `uname` == "Linux" ]; then
   sed="sed -r"
else
   sed="sed -E"
fi

$sed 's#/+#/#g' | \
$sed 's#/([^\t :/]{1,}/){1,}([^\t :/]{1,})#<...>/\2#g'
