#! /usr/bin/env bash
#
# Default canonifier used with the trace-based tests in testing/external/*.

if [ $# != 1 ]; then
    echo "usage: $(basename $0) <filename>"
    exit 1
fi

filename=$(basename $1)

addl="cat"

if [ "$filename" == "capture_loss.log" ]; then
    addl="$(dirname $0)/diff-remove-fractions"
fi

if [ "$filename" == "ssh.log" ]; then
    addl="$(dirname $0)/diff-remove-fields remote_location"
fi

$(dirname $0)/diff-remove-timestamps |
    $(dirname $0)/diff-remove-uids |
    $(dirname $0)/diff-remove-file-ids |
    $(dirname $0)/diff-remove-x509-names |
    $(dirname $0)/diff-sort-conn-service |
    $(dirname $0)/diff-sort-set-elements |
    $(dirname $0)/diff-remove-spicy-abspath |
    $(dirname $0)/diff-sort |
    eval $addl
