#! /usr/bin/env bash
#
# Replace absolute paths with the basename.

if [ $(uname) == "Linux" ]; then
    sed="sed -r"
else
    sed="sed -E"
fi

$sed 's#/+#/#g' |
    $sed 's#[^( ]*testing_btest#<___>testing_btest#' |
    $sed 's#([a-zA-Z]:)?/([^	 :/]{1,}/){1,}([^	 :/]{1,})#<...>/\3#g'
