#! /usr/bin/env bash
#
# doctest's console reports contain several aspects that change over time:
# - The total number of tests, which we replace with "XX"
# - The version number, which becomes "x.y.z"
# - Spacing in the report, which we normalize to single spaces

sed -E -e 's/[0-9]+ skipped/XX skipped/g' |
    sed -E -e 's/"[0-9]+\.[0-9]+\.[0-9]+"/"x.y.z"/g' |
    sed -E -e 's/ {2,}/ /g'
