#! /usr/bin/env bash
#
# Replace absolute paths with the basename.

sed -E 's#/+#/#g' |
    sed -E 's#[^( ]*testing_btest#<___>testing_btest#' |
    sed -E 's#/([^	 :/]{1,}/){1,}([^	 :/]{1,})#<...>/\2#g'
