#! /usr/bin/env bash

# Sleeps until a file comes into existence.

if [[ $# -ne 2 ]]; then
    echo >&2 "usage: $0 <file to wait for> <max secs to wait>"
    exit 1
fi

wait_file=$1
max_wait=$2
wait_count=0

while [[ ! -e $wait_file ]]; do
    let "wait_count += 1"

    if [[ $wait_count -ge $max_wait ]]; then
        echo >&2 "error: file '$wait_file' does not exist after $max_wait seconds"
        exit 1
    fi

    sleep 1
done
