// Generated by binpac_quickstart

#include "plugin/Plugin.h"

#include "NTP.h"

namespace plugin {
namespace Bro_NTP {

class Plugin : public plugin::Plugin {
public:
	plugin::Configuration Configure()
		{
		AddComponent(new ::analyzer::Component("NTP",
		             ::analyzer::NTP::NTP_Analyzer::InstantiateAnalyzer));

		plugin::Configuration config;
		config.name = "Bro::NTP";
		config.description = "Network Time Protocol analyzer";
		return config;
		}
} plugin;

}
}