image_task:
  persistent_worker:
    isolation:
      container:
        image: debian:latest
        cpu: 0.5
        memory: 512
        volumes:
          - /root/.ccache:/root/.ccache

  script: uname -a

dockerfile_task:
  persistent_worker:
    isolation:
      container:
        dockerfile: ci/fedora-37/Dockerfile
        cpu: 0.5
        memory: 512
        volumes:
          - /root/.ccache:/root/.ccache

  script: uname -a

  env:
    CIRRUS_ARCH: amd64
