#!/bin/sh

# This script generates binary RPM packages.
# They can be found in build/ after running.

prefix=/opt/bro

# CMake/CPack versions before 2.8.2 have bugs that can create bad packages
CMAKE_PACK_REQ=2.8.2
CMAKE_VER=`cmake -version`

if [ "${CMAKE_VER}" \< "${CMAKE_PACK_REQ}" ]; then
    echo "Package creation requires CMake > 2.8.2" >&2
    exit 1
fi

# Minimum Bro
./configure --prefix=${prefix} --disable-broccoli --disable-broctl \
            --pkg-name-prefix=Bro --binary-package
( cd build && make package )

# Full Bro package
./configure --prefix=${prefix} --pkg-name-prefix=Bro-all --binary-package
( cd build && make package )

# Broccoli
cd aux/broccoli
./configure --prefix=${prefix} --binary-package
( cd build && make package && mv Broccoli*.rpm ../../../build/ )
cd ../..

# Broctl
cd aux/broctl
./configure --prefix=${prefix} --binary-package
( cd build && make package && mv Broctl*.rpm ../../../build/ )
cd ../..
