module TEST_LOGGING;

@load logging

export {
	# Create a new ID for our log stream
	redef enum Log::ID += { TEST_LOGGING };

	# Define a record with all the columns the log file can have.
	# (I'm using a subset of fields from ssh-ext for demonstration.)
	type Log: record {
		t: time;
		id: conn_id; # Will be rolled out into individual columns.
		status: string &optional;
		country: string &default="unknown";
	};
	
	# This is the prototype for the event that the logging framework tries
	# to generate if there is a handler for it.
	global log: event(rec: Log);
}

event bro_init()
{
	# Create the stream.
	# First argument is the ID for the stream.
	# Second argument is the log record type.
	Log::create_stream("TEST_LOGGING", "TEST_LOGGING::Log");

	# Add a default filter that simply logs everything to "ssh.log" using the default writer.
	# Log line event generation is autogenerated for now by checking for 
	# handlers for MODULE_NAME::log (which isn't the right thing to do, but it will be dealt with later)
	Log::add_default_filter("TEST_LOGGING");
	
	# There is currently some problem with &optional values in the records 
	# passed into the predicate.  Maybe it's because I'm not really coercing
	# the record to the correct record type before passing it as an argument
	# to the Call method?
	
	# There is also a problem with using &optional sets in the filter records.
	#   It was found when trying to include the "select" variable.
	
	# Printing headers for the filters doesn't work yet either and needs to 
	# be considered in the final design. (based on the "select" set).
	#Log::add_filter("ssh", [$name="successful logins",
	#                            #$pred(rec: Log) = { print rec$status; return T; },
	#                            $path="ssh-logins",
	#                            #$select=set("t"),
	#                            $writer=Log::WRITER_CSV]);
	
	# Log something.
	Log::write("TEST_LOGGING", [$t=network_time(),$status="success"]);
	Log::write("TEST_LOGGING", [$t=network_time(),$status="failure", $country="US"]);
	Log::write("TEST_LOGGING", [$t=network_time(),$status="failure", $country="UK"]);
	Log::write("TEST_LOGGING", [$t=network_time(),$status="success", $country="BR"]);
	Log::write("TEST_LOGGING", [$t=network_time(),$status="failure", $country="MX"]);
	
}

#event log(rec: Log)
#	{
#	print fmt("Ran the log handler from the same module.  Extracting time: %0.6f", rec$t);
#	}
#
#
#module WHATEVER;
#
#event SSH::log(rec: SSH::Log)
#	{
#	print fmt("Ran the SSH::log handler from a different module.  Extracting time: %0.6f", rec$t);
#	}