# Generated by binpac_quickstart

refine flow C12_22_Flow += {
	function proc_c12_22_message(msg: C12_22_PDU): bool
		%{
		BifEvent::generate_c12_22_event(connection()->bro_analyzer(), connection()->bro_analyzer()->Conn());
		return true;
		%}
};

refine typeattr C12_22_PDU += &let {
	proc: bool = $context.flow.proc_c12_22_message(this);
};