#!/usr/bin/env python3
"""
Generate a pcap with truncated ICMPv6 NDP packets that exercise
the length checks added before BuildNDOptionsVal calls in ICMP.cc.

Each packet is truncated so that caplen (bytes after the 8-byte ICMPv6
header) is shorter than the expected option offset:
  - Router Advertisement: opt_offset = 8 (reachable_time + retrans_timer)
  - Neighbor Advertisement: opt_offset = 16 (target address)
  - Neighbor Solicitation: opt_offset = 16 (target address)
  - Redirect: opt_offset = 32 (target + destination addresses)

Generated by Claude Opus 4.6 (Anthropic), adapted with Claude Sonnet 5.5
(Anthropic) to write beside the script, use Scapy's checksum helper and fixed
timestamps so the trace is reproducible.
"""

from pathlib import Path

from scapy.all import (
    Ether,
    ICMPv6ND_NA,
    ICMPv6ND_NS,
    ICMPv6ND_RA,
    ICMPv6ND_Redirect,
    ICMPv6NDOptSrcLLAddr,
    IPv6,
    Raw,
    in6_chksum,
    wrpcap,
)

BASE_TIME = 1_700_000_000.0

SRC_MAC = "00:11:22:33:44:55"
DST_MAC = "00:66:77:88:99:aa"


def truncate_icmpv6_payload(pkt, keep_icmp_payload_bytes):
    """Build a packet where the ICMPv6 body is truncated to
    `keep_icmp_payload_bytes` after the 8-byte ICMPv6 header.
    The IPv6 payload length and ICMPv6 checksum are recomputed
    so Zeek accepts the packet without flagging truncation or
    bad checksums."""
    icmp_hdr_len = 8
    ip = pkt[IPv6]
    body = bytearray(bytes(ip.payload)[: icmp_hdr_len + keep_icmp_payload_bytes])

    # Recompute the ICMPv6 checksum over the truncated content.
    body[2:4] = b"\x00\x00"
    cksum = in6_chksum(58, IPv6(src=ip.src, dst=ip.dst), bytes(body))
    body[2:4] = cksum.to_bytes(2, "big")

    # The IPv6 payload length is filled in by Scapy from the truncated body.
    return (
        Ether(src=pkt[Ether].src, dst=pkt[Ether].dst)
        / IPv6(src=ip.src, dst=ip.dst, nh=58, hlim=ip.hlim)
        / Raw(bytes(body))
    )


def main():
    packets = []
    src_mac = SRC_MAC
    dst_mac = DST_MAC
    src_ip = "fe80::1"
    dst_ip = "fe80::2"
    target = "fe80::3"

    # --- Router Advertisement: opt_offset = 8 (sizeof(uint32_t)*2) ---
    # Truncate to 4 bytes of payload (less than 8) to trigger icmp6_ra_bad_opt_offset
    ra = (
        Ether(src=src_mac, dst=dst_mac)
        / IPv6(src=src_ip, dst="ff02::1")
        / ICMPv6ND_RA()
    )
    packets.append(truncate_icmpv6_payload(ra, 4))

    # Also include a valid RA for comparison (full payload with options)
    ra_good = (
        Ether(src=src_mac, dst=dst_mac)
        / IPv6(src=src_ip, dst="ff02::1")
        / ICMPv6ND_RA()
        / ICMPv6NDOptSrcLLAddr(lladdr=src_mac)
    )
    packets.append(ra_good)

    # --- Neighbor Advertisement: opt_offset = 16 (sizeof(in6_addr)) ---
    # Truncate to 8 bytes of payload (less than 16) to trigger icmp6_na_bad_opt_offset
    na = (
        Ether(src=src_mac, dst=dst_mac)
        / IPv6(src=src_ip, dst=dst_ip)
        / ICMPv6ND_NA(tgt=target)
    )
    packets.append(truncate_icmpv6_payload(na, 8))

    # Valid NA
    na_good = (
        Ether(src=src_mac, dst=dst_mac)
        / IPv6(src=src_ip, dst=dst_ip)
        / ICMPv6ND_NA(tgt=target)
        / ICMPv6NDOptSrcLLAddr(lladdr=src_mac)
    )
    packets.append(na_good)

    # --- Neighbor Solicitation: opt_offset = 16 (sizeof(in6_addr)) ---
    # Truncate to 8 bytes of payload (less than 16) to trigger icmp6_ns_bad_opt_offset
    ns = (
        Ether(src=src_mac, dst=dst_mac)
        / IPv6(src=src_ip, dst="ff02::1:ff00:3")
        / ICMPv6ND_NS(tgt=target)
    )
    packets.append(truncate_icmpv6_payload(ns, 8))

    # Valid NS
    ns_good = (
        Ether(src=src_mac, dst=dst_mac)
        / IPv6(src=src_ip, dst="ff02::1:ff00:3")
        / ICMPv6ND_NS(tgt=target)
        / ICMPv6NDOptSrcLLAddr(lladdr=src_mac)
    )
    packets.append(ns_good)

    # --- Redirect: opt_offset = 32 (2 * sizeof(in6_addr)) ---
    # Truncate to 16 bytes of payload (less than 32) to trigger icmp6_redirect_bad_opt_offset
    redirect = (
        Ether(src=src_mac, dst=dst_mac)
        / IPv6(src=src_ip, dst=dst_ip)
        / ICMPv6ND_Redirect(tgt=target, dst="2001:db8::1")
    )
    packets.append(truncate_icmpv6_payload(redirect, 16))

    # Valid Redirect
    redirect_good = (
        Ether(src=src_mac, dst=dst_mac)
        / IPv6(src=src_ip, dst=dst_ip)
        / ICMPv6ND_Redirect(tgt=target, dst="2001:db8::1")
        / ICMPv6NDOptSrcLLAddr(lladdr=src_mac)
    )
    packets.append(redirect_good)

    # --- Edge cases: payload exactly at the boundary (should NOT trigger) ---
    # RA with exactly 8 bytes payload (just enough)
    packets.append(truncate_icmpv6_payload(ra, 8))

    # NA with exactly 16 bytes payload (just enough)
    packets.append(truncate_icmpv6_payload(na, 16))

    # NS with exactly 16 bytes payload (just enough)
    ns_full_hdr = (
        Ether(src=src_mac, dst=dst_mac)
        / IPv6(src=src_ip, dst="ff02::1:ff00:3")
        / ICMPv6ND_NS(tgt=target)
    )
    packets.append(truncate_icmpv6_payload(ns_full_hdr, 16))

    # Redirect with exactly 32 bytes payload (just enough)
    packets.append(truncate_icmpv6_payload(redirect, 32))

    # --- Zero-length payloads (most extreme truncation) ---
    # Note: Zeek deduplicates net-level weirds by name, so these won't
    # produce additional weird.log entries unless sampling is disabled.
    # They still exercise the code path.
    ra_zero = (
        Ether(src=src_mac, dst=dst_mac)
        / IPv6(src="fe80::10", dst="ff02::1")
        / ICMPv6ND_RA()
    )
    packets.append(truncate_icmpv6_payload(ra_zero, 0))

    na_zero = (
        Ether(src=src_mac, dst=dst_mac)
        / IPv6(src="fe80::10", dst=dst_ip)
        / ICMPv6ND_NA(tgt=target)
    )
    packets.append(truncate_icmpv6_payload(na_zero, 0))

    ns_zero = (
        Ether(src=src_mac, dst=dst_mac)
        / IPv6(src="fe80::10", dst="ff02::1:ff00:3")
        / ICMPv6ND_NS(tgt=target)
    )
    packets.append(truncate_icmpv6_payload(ns_zero, 0))

    redirect_zero = (
        Ether(src=src_mac, dst=dst_mac)
        / IPv6(src="fe80::10", dst=dst_ip)
        / ICMPv6ND_Redirect(tgt=target, dst="2001:db8::1")
    )
    packets.append(truncate_icmpv6_payload(redirect_zero, 0))

    for index, p in enumerate(packets):
        p.time = BASE_TIME + index * 0.001

    wrpcap(str(Path(__file__).with_suffix("")), packets)


if __name__ == "__main__":
    main()
