### BTest baseline data generated by btest-diff. Do not edit. Use "btest -U/-u" to update. Requires BTest >= 0.63.
version = "1.0.0.dev2",  # short
version = "1.0.0.dev2",  # with dev update
version = "1.0.0.dev2",  # long
version = "1.0.0.dev2",  # long with dev update
version = "1.0.0.dev2",  # Python style
version = "0.0.1.nope"   # should not change, invalid suffix
print('Additional change')
