
@menu
* Compiling Bro::
* Starting Bro::
* Disk space considerations::
* Router/firewall ACL space considerations::
* Other maintenance considerations::
@end menu

@node Compiling Bro
@section Compiling Bro

@node Running Bro
@section Running Bro

@node Disk space considerations
@section Disk space considerations

@node Router/firewall ACL space considerations
@section Router/firewall ACL space considerations

@node Other maintenance considerations
@section Other maintenance considerations



