#!/usr/bin/env python3
"""
This was entirely generated by Claude code, adapted by Claude Sonnet 5.5
(Anthropic) to use Scapy's DCE-RPC layer, a deterministic timestamp and to write
next to the script.

Generate a DCE-RPC Bind / Bind-ACK pcap with a sec_addr that has NO trailing null.

Before the patch  (line 90 original):
  *(begin() + length()) == 0  --> always true (binpac null terminator)
  --> sec_addr is ALWAYS truncated by 1 byte, even for b"ABC" -> "AB"

After the patch (line 90 patched):
  *(begin() + length() - 1) == 0  --> false for b"ABC"
  --> sec_addr is kept as-is: "ABC"

Packets built per flow:
  Pkt 1  b'ABC'      old=b'AB'   new=b'ABC'  <- behavior change
  Pkt 2  b'ABC\\x00'  old=b'ABC'  new=b'ABC'  <- same (no change)
  Pkt 3  b'X'        old=b''     new=b'X'    <- behavior change
"""

import uuid
from pathlib import Path

from scapy.all import IP, TCP, Ether, Raw, wrpcap
from scapy.layers.dcerpc import (
    DceRpc5,
    DceRpc5AbstractSyntax,
    DceRpc5Bind,
    DceRpc5BindAck,
    DceRpc5Context,
    DceRpc5PortAny,
    DceRpc5Result,
    DceRpc5TransferSyntax,
)

BASE_TIME = 1_700_000_000.0
SERVER_IP = "10.0.0.1"
SERVER_PORT = 135

# NDR 2.0 transfer syntax: 8a885d04-1ceb-11c9-9fe8-08002b104860
NDR_UUID = uuid.UUID("8a885d04-1ceb-11c9-9fe8-08002b104860")
# A dummy abstract syntax UUID
ABS_UUID = uuid.UUID("12345678-1234-abcd-ef00-0123456789ab")


def dce_rpc(ptype, body):
    """Little-endian DCE-RPC PDU that is both first and last fragment."""
    return DceRpc5(ptype=ptype, pfc_flags=0x03, endian="little", call_id=1) / body


def build_bind():
    return dce_rpc(
        "bind",
        DceRpc5Bind(
            max_xmit_frag=4280,
            max_recv_frag=4280,
            assoc_group_id=0,
            context_elem=[
                DceRpc5Context(
                    cont_id=0,
                    abstract_syntax=DceRpc5AbstractSyntax(
                        if_uuid=ABS_UUID, if_version=1
                    ),
                    transfer_syntaxes=[
                        DceRpc5TransferSyntax(if_uuid=NDR_UUID, if_version=2)
                    ],
                )
            ],
        ),
    )


def build_bind_ack(sec_addr):
    return dce_rpc(
        "bind_ack",
        DceRpc5BindAck(
            max_xmit_frag=4280,
            max_recv_frag=4280,
            assoc_group_id=0x12345678,
            sec_addr=DceRpc5PortAny(port_spec=sec_addr),
            results=[
                DceRpc5Result(
                    result=0,
                    reason=0,
                    transfer_syntax=DceRpc5TransferSyntax(
                        if_uuid=NDR_UUID, if_version=2
                    ),
                )
            ],
        ),
    )


def make_flow(sec_addr, client_ip, sport, seq_c=100, seq_s=200):
    """Return [syn, syn-ack, ack, bind, bind_ack] for one flow."""

    def packet(src_ip, dst_ip, src_port, dst_port, flags, seq, ack, payload=b""):
        pkt = (
            Ether(src="aa:bb:cc:dd:ee:01", dst="aa:bb:cc:dd:ee:02")
            / IP(src=src_ip, dst=dst_ip)
            / TCP(sport=src_port, dport=dst_port, flags=flags, seq=seq, ack=ack)
        )
        return pkt / Raw(load=payload) if payload else pkt

    bind = bytes(build_bind())
    bind_ack = bytes(build_bind_ack(sec_addr))
    dport = SERVER_PORT

    return [
        packet(client_ip, SERVER_IP, sport, dport, "S", seq_c, 0),
        packet(SERVER_IP, client_ip, dport, sport, "SA", seq_s, seq_c + 1),
        packet(client_ip, SERVER_IP, sport, dport, "A", seq_c + 1, seq_s + 1),
        packet(client_ip, SERVER_IP, sport, dport, "PA", seq_c + 1, seq_s + 1, bind),
        packet(
            SERVER_IP,
            client_ip,
            dport,
            sport,
            "PA",
            seq_s + 1,
            seq_c + 1 + len(bind),
            bind_ack,
        ),
    ]


def main():
    packets = []

    # Flow 1: sec_addr = b'ABC'  (no null) -> old strips to "AB", new keeps "ABC"
    packets += make_flow(b"ABC", client_ip="10.0.0.2", sport=49152)

    # Flow 2: sec_addr = b'ABC\x00' (null)  -> both old and new produce "ABC"
    packets += make_flow(b"ABC\x00", client_ip="10.0.0.3", sport=49153)

    # Flow 3: sec_addr = b'X'    (no null) -> old strips to "",  new keeps "X"
    packets += make_flow(b"X", client_ip="10.0.0.4", sport=49154)

    for index, pkt in enumerate(packets):
        pkt.time = BASE_TIME + index * 0.001

    wrpcap(str(Path(__file__).with_suffix("")), packets)


if __name__ == "__main__":
    main()
