version: 2.1
setup: true

orbs:
  continuation: circleci/continuation@2.0.1

jobs:
  setup_job:
    docker:
      - image: cimg/python:3.10
    steps:
      # TODO: this needs to skip the job entirely if the only files that changed were
      # docs.
      - checkout
      - run:
          name: Generate workflow parameters
          command: .circleci/generate-workflow-params.py
      - continuation/continue:
          configuration_path: .circleci/builds.yml
          parameters: /tmp/parameters.json

workflows:
  setup:
    when:
      or:
        - equal: [ "pull_request", << pipeline.event.name >> ]
        - and:
          # The check for the trigger type here prevents us from doing double builds on
          # pushes to master. We only want to do them from the oauth trigger, which
          # covers pushes to the default branch.
          - equal: [ master, << pipeline.git.branch >> ]
          - equal: [ github_oauth, << pipeline.trigger.type >> ]
        - matches:
            pattern: "^release/.*"
            value: << pipeline.git.branch >>
        - and:
          # Similar to above, we only want one build to trigger off tag pushes.
          - matches:
              pattern: ^v[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?$
              value: << pipeline.git.tag >>
          - equal: [ github_oauth, << pipeline.trigger.type >> ]
        - equal: [ "nightly", << pipeline.schedule.name >> ]
        - equal: [ "weekly", << pipeline.schedule.name >> ]
    jobs:
      - setup_job
