version: 2.1
setup: true

orbs:
  continuation: circleci/continuation@2.0.1

jobs:
  setup_job:
    docker:
      - image: cimg/python:3.10
    steps:
      # TODO: this needs to skip the job entirely if the only files that changed were
      # docs.
      - checkout
      - run:
          name: Generate workflow parameters
          command: .circleci/generate-workflow-params.py
      - continuation/continue:
          configuration_path: .circleci/config.yml
          parameters: /tmp/parameters.json

workflows:
  setup:
    when:
      or:
        - equal: [ "pull_request", << pipeline.event.name >> ]
        - and:
          # The check for the trigger here prevents us from doing double builds on pushes
          # to master. If the all-pushes trigger is deleted or recreated from the project
          # this needs to be fixed.
          - equal: [ master, << pipeline.git.branch >> ]
          - equal: [ f5314bc7-fc82-4458-bd27-fc73c71e5a73, << pipeline.trigger.id >> ]
        - matches:
            pattern: "^release/.*"
            value: << pipeline.git.branch >>
        - matches:
            pattern: "^v[0-9]+\\.[0-9]+\\.[0-9]+(-rc[0-9]+)?$"
            value: << pipeline.git.tag >>
        - equal: [ "nightly", << pipeline.schedule.name >> ]
        - equal: [ "weekly", << pipeline.schedule.name >> ]
    jobs:
      - setup_job
