version: 2.1
setup: true

orbs:
  continuation: circleci/continuation@2.0.1

jobs:
  setup_job:
    docker:
      - image: cimg/python:3.10
    steps:
      # TODO: this needs to skip the job entirely if the only files that changed were
      # docs.
      - checkout
      - run:
          name: Generate workflow parameters
          command: .circleci/generate-workflow-params.py
      - continuation/continue:
          configuration_path: .circleci/config.yml
          parameters: /tmp/parameters.json

workflows:
  setup:
    when:
      or:
        - equal: [ "pull_request", << pipeline.event.name >> ]
        - and:
          # The check for the trigger here prevents us from doing double builds on pushes
          # to master. If the all-pushes trigger is deleted or recreated from the project
          # this needs to be fixed. See below for more docs on how to get this ID.
          - equal: [ master, << pipeline.git.branch >> ]
          - or:
            - equal: [ 593abe2f-5739-4f75-99de-b3afb2ee099d, << pipeline.trigger.id >> ] # zeek
            - equal: [ 338ccf41-69c6-4c4f-a0cf-7be8fdd74bd3, << pipeline.trigger.id >> ] # zeek-security
        - matches:
            pattern: "^release/.*"
            value: << pipeline.git.branch >>
        - matches:
            pattern: "^v[0-9]+\\.[0-9]+\\.[0-9]+(-rc[0-9]+)?$"
            value: << pipeline.git.tag >>
        - equal: [ "nightly", << pipeline.schedule.name >> ]
        - equal: [ "weekly", << pipeline.schedule.name >> ]
    jobs:
      - setup_job


# To get the ID for the trigger above, you must go through the CircleCI API. It doesn't
# show up anywhere on the UI that I have found. This requires a bit of gymnastics. You'll
# need the following:
# - A personal access token on your CircleCI account
# - The project ID, available from the "Overview" page for the project on the site
# - The pipeline ID, available from the "Project Setup" page for the project on the site.
#   The ID is right under the title of the pipeline.
#
# Make a request to the API like such:
#   curl --request GET \
#     --url https://circleci.com/api/v2/projects/<project id>/pipeline-definitions/<pipeline id>/trigger \
#     --header "Circle-Token: $CIRCLE_TOKEN"
#
# Find the ID for the "all-pushes" trigger in the output. Alternatively, you can use the
# "only-build-prs" trigger. It doesn't really matter, because we're just using one of the
# IDs to avoid doing builds for master from both triggers.
