### BTest baseline data generated by btest-diff. Do not edit. Use "btest -U/-u" to update. Requires BTest >= 0.63.
VERSION="1.0.0-2"
VERSION="1.0.0-2"
VERSION="1.0.0-2"
VERSION="1.0.0-2"
  VERSION = "1.0.0-2"  # with some comment
  VERSION = "2.0.0-nope"  # with some comment
...
