"""
Generated by GPT 5.5 to provoke a growing DHCP::join_data table.
"""

import struct

from scapy.all import BOOTP, IP, UDP, Ether, Raw, wrpcapng


def dhcp_request(xid, ts):
    bootp = BOOTP(
        op=1,
        htype=1,
        hlen=6,
        hops=0,
        xid=xid,
        flags=0x8000,
        # Make chaddr dependent on the xid.
        chaddr=b"\x02\x00\x00\x00" + struct.pack(">h", xid % 2**16),
    )
    options = b"\x35\x01\x01\xff"
    pkt = (
        Ether(src="02:00:00:00:00:01", dst="ff:ff:ff:ff:ff:ff")
        / IP(src="0.0.0.0", dst="255.255.255.255")
        / UDP(sport=68, dport=67)
        / bootp
        / Raw(load=b"\x63\x82\x53\x63" + options)
    )
    pkt.time = ts
    return pkt


packets = [dhcp_request(0x30000000 + i, 1700000100 + i * 0.0001) for i in range(50)]
wrpcapng("dhcp-unique-xid-join-data-growth.pcapng", packets)
