// Generated by binpac_quickstart

#ifndef ANALYZER_PROTOCOL_OPCUA_OPCUA_H
#define ANALYZER_PROTOCOL_OPCUA_OPCUA_H

#include "events.bif.h"


#include "analyzer/protocol/tcp/TCP.h"

#include "opcua_pac.h"

namespace analyzer { namespace OPCUA {

class OPCUA_Analyzer

: public tcp::TCP_ApplicationAnalyzer {

public:
	OPCUA_Analyzer(Connection* conn);
	virtual ~OPCUA_Analyzer();

	// Overriden from Analyzer.
	virtual void Done();

	virtual void DeliverStream(int len, const u_char* data, bool orig);
	virtual void Undelivered(uint64 seq, int len, bool orig);

	// Overriden from tcp::TCP_ApplicationAnalyzer.
	virtual void EndpointEOF(bool is_orig);


	static analyzer::Analyzer* InstantiateAnalyzer(Connection* conn)
		{ return new OPCUA_Analyzer(conn); }

protected:
	binpac::OPCUA::OPCUA_Conn* interp;

	bool had_gap;

};

} } // namespace analyzer::*

#endif
