### BTest baseline data generated by btest-diff. Do not edit. Use "btest -U/-u" to update. Requires BTest >= 0.63.
#define   ZEEK_VERSION "1.0.0-2" /* with comment */
#define   ZEEK_VERSION "1.0.0-2" /* with comment */
  #define FOO_VERSION  "1.0.0-2" // another comment
...
