
#include "plugin/Plugin.h"

#include "DCE_RPC.h"

BRO_PLUGIN_BEGIN(Bro, DCE_RPC)
	BRO_PLUGIN_DESCRIPTION("DCE-RPC analyzer");
	BRO_PLUGIN_ANALYZER("DCE_RPC", dce_rpc::DCE_RPC_Analyzer);
	BRO_PLUGIN_SUPPORT_ANALYZER("Contents_DCE_RPC");
	BRO_PLUGIN_BIF_FILE(events);
BRO_PLUGIN_END
