# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _SubnetTree
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


class SubnetTree(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SubnetTree, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SubnetTree, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _SubnetTree.new_SubnetTree(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _SubnetTree.delete_SubnetTree
    __del__ = lambda self : None;
    def insert(*args): return _SubnetTree.SubnetTree_insert(*args)
    def remove(*args): return _SubnetTree.SubnetTree_remove(*args)
    def lookup(*args): return _SubnetTree.SubnetTree_lookup(*args)
    def __contains__(*args): return _SubnetTree.SubnetTree___contains__(*args)
    def __getitem__(*args): return _SubnetTree.SubnetTree___getitem__(*args)
    def __setitem__(*args): return _SubnetTree.SubnetTree___setitem__(*args)
    def __delitem__(*args): return _SubnetTree.SubnetTree___delitem__(*args)
SubnetTree_swigregister = _SubnetTree.SubnetTree_swigregister
SubnetTree_swigregister(SubnetTree)



