#! /bin/sh

build=../../../build

echo > CPP-gen-addl.h
(cd $build
 export -n ZEEK_USE_CPP ZEEK_ADD_CPP
 export ZEEK_HASH_DIR=.
 echo | src/zeek -b -O gen-C++
)
mv $build/CPP-gen-addl.h CPP-gen.cc
(cd $build ; ninja || echo Bare embedded build failed)
