#! /bin/sh

base=../../..
test=$base/testing/btest
so=$base/src/script_opt/CPP
build=$base/build
gen=CPP-gen-addl.h

export -n ZEEK_USE_CPP
export ZEEK_HASH_DIR=$test ZEEK_ADD_CPP=
cd $test
cp $build/CPP-hashes.dat .
echo >$gen
../../auxil/btest/btest $1 >test-suite-build.out 2>&1
grep -c '^namespace' $gen
mv $gen $so
cd $build
ninja >& errs || echo test suite build failed
