#!/usr/bin/env python3

"""Generate an LDAP trace with many outstanding SearchRequest message IDs.

The trace contains one TCP connection to port 389. The client sends many valid
LDAP SearchRequest messages with unique message IDs and no SearchResultDone
responses. Zeek's LDAP script retains one pending SearchInfo record per message
ID until connection removal.

Generated by ChatGPT-5.5 (Codex).
The message count is fixed at 10 (the committed trace) and packets carry fixed
timestamps, so running the script reproduces pending-searches-10.pcap exactly.
"""

from __future__ import annotations

from pathlib import Path

from scapy.all import IP, TCP, Ether, wrpcap

BASE_TIME = 1_700_000_000.0
COUNT = 10
CHUNK_SIZE = 1200
BASE_OBJECT = ""
FILTER_ATTR = "objectClass"


def ber_len(length: int) -> bytes:
    if length < 0x80:
        return bytes([length])

    encoded = length.to_bytes((length.bit_length() + 7) // 8, "big")
    return bytes([0x80 | len(encoded)]) + encoded


def tlv(tag: int, value: bytes) -> bytes:
    return bytes([tag]) + ber_len(len(value)) + value


def ber_int(value: int) -> bytes:
    encoded = value.to_bytes((value.bit_length() + 7) // 8 or 1, "big")

    if encoded[0] & 0x80:
        encoded = b"\x00" + encoded

    return tlv(0x02, encoded)


def ldap_search_request(message_id: int, base_object: str, filter_attr: str) -> bytes:
    """Build an LDAPMessage containing a minimal SearchRequest.

    SearchRequest ASN.1:

        [APPLICATION 3] SEQUENCE {
            baseObject      LDAPDN,
            scope           ENUMERATED,
            derefAliases    ENUMERATED,
            sizeLimit       INTEGER,
            timeLimit       INTEGER,
            typesOnly       BOOLEAN,
            filter          Filter,
            attributes      AttributeSelection
        }

    The filter is a present filter, e.g. (objectClass=*), encoded as [7].
    """

    request_body = b"".join(
        [
            tlv(0x04, base_object.encode("utf-8")),
            tlv(0x0A, b"\x02"),  # wholeSubtree
            tlv(0x0A, b"\x00"),  # neverDerefAliases
            ber_int(0),  # no size limit
            ber_int(0),  # no time limit
            tlv(0x01, b"\x00"),  # typesOnly = false
            tlv(0x87, filter_attr.encode("utf-8")),  # present filter
            tlv(0x30, b""),  # no requested attributes
        ]
    )

    return tlv(0x30, ber_int(message_id) + tlv(0x63, request_body))


def build_packets(count: int, chunk_size: int, base_object: str, filter_attr: str):
    client = "10.0.0.1"
    server = "10.0.0.2"
    client_mac = "02:00:00:00:00:01"
    server_mac = "02:00:00:00:00:02"
    sport = 50000
    dport = 389
    client_seq = 1000
    server_seq = 9000

    packets = [
        Ether(src=client_mac, dst=server_mac)
        / IP(src=client, dst=server)
        / TCP(sport=sport, dport=dport, flags="S", seq=client_seq),
        Ether(src=server_mac, dst=client_mac)
        / IP(src=server, dst=client)
        / TCP(sport=dport, dport=sport, flags="SA", seq=server_seq, ack=client_seq + 1),
        Ether(src=client_mac, dst=server_mac)
        / IP(src=client, dst=server)
        / TCP(
            sport=sport, dport=dport, flags="A", seq=client_seq + 1, ack=server_seq + 1
        ),
    ]

    payload = b"".join(
        ldap_search_request(i, base_object, filter_attr) for i in range(1, count + 1)
    )

    seq = client_seq + 1
    for offset in range(0, len(payload), chunk_size):
        chunk = payload[offset : offset + chunk_size]
        packets.append(
            Ether(src=client_mac, dst=server_mac)
            / IP(src=client, dst=server)
            / TCP(sport=sport, dport=dport, flags="PA", seq=seq, ack=server_seq + 1)
            / chunk
        )
        seq += len(chunk)

    return packets, len(payload)


def main() -> None:
    packets, _ = build_packets(COUNT, CHUNK_SIZE, BASE_OBJECT, FILTER_ATTR)

    for index, p in enumerate(packets):
        p.time = BASE_TIME + index * 0.001

    wrpcap(str(Path(__file__).with_suffix("")), packets)


if __name__ == "__main__":
    main()
