
#include "plugin/Plugin.h"

#include "FTP.h"

BRO_PLUGIN_BEGIN(Bro, FTP)
	BRO_PLUGIN_DESCRIPTION("FTP analyzer");
	BRO_PLUGIN_ANALYZER("FTP", ftp::FTP_Analyzer);
	BRO_PLUGIN_SUPPORT_ANALYZER("FTP_ADAT");
	BRO_PLUGIN_BIF_FILE(events);
	BRO_PLUGIN_BIF_FILE(functions);
BRO_PLUGIN_END
