#!/usr/bin/env python3
"""
Generate netbios-split-session-msg.pcap: a NetBIOS-over-TCP session where a
message body is split across two TCP payload packets. The second TCP payload
completes the split body and then carries a second complete NetBIOS message.

This exercises Contents_NetbiosSSN::ProcessChunk() body buffering: after the
first TCP payload the analyzer has allocated and buffered only part of the
declared message body. The next ProcessChunk() call should append the remaining
body bytes, parse that message, reset to header parsing, and parse the second
message from the bytes still left in the TCP payload.

Generated by GPT-5 (OpenAI).
"""

import argparse
from pathlib import Path

from scapy.all import IP, TCP, Ether, wrpcap

CLIENT_IP = "10.0.0.1"
SERVER_IP = "10.0.0.2"
CLIENT_PORT = 54321
SERVER_PORT = 139  # NetBIOS session service

NETBIOS_SSN_MESSAGE = 0x00


def pkt(src_ip, dst_ip, sport, dport, flags, seq, ack, payload=b""):
    return (
        Ether(src="00:00:00:00:00:01", dst="00:00:00:00:00:02")
        / IP(src=src_ip, dst=dst_ip)
        / TCP(sport=sport, dport=dport, flags=flags, seq=seq, ack=ack)
        / payload
    )


def cpkt(flags, seq, ack, payload=b""):
    return pkt(CLIENT_IP, SERVER_IP, CLIENT_PORT, SERVER_PORT, flags, seq, ack, payload)


def spkt(flags, seq, ack, payload=b""):
    return pkt(SERVER_IP, CLIENT_IP, SERVER_PORT, CLIENT_PORT, flags, seq, ack, payload)


def netbios_header(msg_type, msg_size):
    """Four-byte NetBIOS session header declaring msg_size body bytes."""
    return bytes([msg_type, 0x00, (msg_size >> 8) & 0xFF, msg_size & 0xFF])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).with_suffix(""),
        help="output pcap path (default: this script's name without .py)",
    )
    args = parser.parse_args()

    first_body = b"\xffSMB" + b"A" * 28
    second_body = b"\xffSMB"

    first_msg = netbios_header(NETBIOS_SSN_MESSAGE, len(first_body)) + first_body
    second_msg = netbios_header(NETBIOS_SSN_MESSAGE, len(second_body)) + second_body

    first_tcp_payload = first_msg[:8]
    second_tcp_payload = first_msg[8:] + second_msg

    c_seq = 1000
    s_seq = 2000

    pkts = []

    # Three-way handshake so the stream reassembler engages.
    pkts.append(cpkt("S", c_seq, 0))
    c_seq += 1
    pkts.append(spkt("SA", s_seq, c_seq))
    s_seq += 1
    pkts.append(cpkt("A", c_seq, s_seq))

    # Header plus only the first four body bytes.
    pkts.append(cpkt("PA", c_seq, s_seq, first_tcp_payload))
    c_seq += len(first_tcp_payload)
    pkts.append(spkt("A", s_seq, c_seq))

    # Remaining first-message body bytes, then another complete message.
    pkts.append(cpkt("PA", c_seq, s_seq, second_tcp_payload))
    c_seq += len(second_tcp_payload)
    pkts.append(spkt("A", s_seq, c_seq))

    pkts.append(cpkt("FA", c_seq, s_seq))
    c_seq += 1
    pkts.append(spkt("FA", s_seq, c_seq))
    s_seq += 1
    pkts.append(cpkt("A", c_seq, s_seq))

    wrpcap(str(args.output), pkts)
    print(f"Wrote {len(pkts)} packets to {args.output}")


if __name__ == "__main__":
    main()
