#!/usr/bin/env python3
"""
Generate max-compression-depth.pcap — a DNS response with 7 answer RRs where
each successive RR's name is a compression pointer to the previous RR's name,
building a backward chain deep enough to exceed dns_max_compression_chain_depth.

Set dns_max_compression_chain_depth=5 in the test; the chain reaches depth 6.

Chain when resolving RR6's name:
  ExtractName(RR6.name, depth=0) -> ptr->RR5 -> ExtractName(depth=1)
    -> ptr->RR4 -> ExtractName(depth=2) -> ... -> ExtractName(depth=6) > 5 -> weird

All pointers target strictly earlier offsets so the forward-pointer check
(DNS_label_forward_compress_offset) is never hit.

Generated by Claude Sonnet 4.6 (Anthropic), adapted by Claude Sonnet 5.5
(Anthropic) to use Scapy's DNS layer and a deterministic timestamp.
"""

from pathlib import Path

from scapy.all import DNS, DNSQR, DNSRR, IP, UDP, Ether, wrpcap

SRC = "1.2.3.4"
DST = "5.6.7.8"
SMAC = "02:00:00:00:00:01"
DMAC = "02:00:00:00:00:02"
BASE_TIME = 1_700_000_000.0

# Packet layout (offsets from start of DNS payload):
#   [0..11]   DNS header (qdcount=1, ancount=7)
#   [12..14]  question name: \x01a\x00
#   [15..18]  qtype=A, qclass=IN
#   [19..35]  RR0: name=\x01a\x00 (3 bytes), type A, 4-byte rdata  (17 bytes)
#   [36..51]  RR1: name=ptr->19,  type A, 4-byte rdata             (16 bytes)
#   [52..67]  RR2: name=ptr->36, ...
#   [68..83]  RR3: name=ptr->52
#   [84..99]  RR4: name=ptr->68
#   [100..115] RR5: name=ptr->84
#   [116..131] RR6: name=ptr->100  <- resolving this fires the weird
POINTER_TARGETS = [19, 36, 52, 68, 84, 100]


def ptr(offset):
    """2-byte DNS compression pointer."""
    return bytes([0xC0 | (offset >> 8), offset & 0xFF])


def answer(name, index):
    return DNSRR(
        rrname=name, type="A", rclass="IN", ttl=300, rdata=f"127.0.0.{index + 1}"
    )


def main():
    # RR0 carries the real label; RR1..RR6 each point at the previous RR's name.
    answers = [answer("a.", 0)]
    answers += [answer(ptr(off), i + 1) for i, off in enumerate(POINTER_TARGETS)]

    pkt = (
        Ether(src=SMAC, dst=DMAC)
        / IP(src=SRC, dst=DST)
        / UDP(sport=12345, dport=53)
        / DNS(
            id=0x1234,
            qr=1,
            rd=1,
            ra=1,
            qd=DNSQR(qname="a.", qtype="A", qclass="IN"),
            an=answers,
        )
    )
    pkt.time = BASE_TIME

    wrpcap(str(Path(__file__).with_suffix("")), [pkt])


if __name__ == "__main__":
    main()
