#!/usr/bin/env python3
"""
Generate svcb-alpn-malformed-len.pcap with two DNS HTTPS/SVCB query/response
connections, each containing a malformed ALPN SvcParam encoding:

  client port 1234: the h3 length byte overshoots the value (8 instead of 2)
  client port 1235: the h3 length byte undershoots the value (1 instead of 2),
                    which leaves a trailing byte

Generated by Claude Opus 4.6 (Anthropic), merged from the former
svcb-alpn-malformed-len-too-{long,short}.pcap and adapted by Claude Sonnet 5.5
(Anthropic) to use fixed MACs and timestamps.
"""

import struct
from pathlib import Path

from scapy.all import DNS, DNSQR, DNSRR, IP, UDP, Ether, wrpcap

SVCB_KEY_ALPN = 1
CLIENT_MAC = "02:00:00:00:00:01"
SERVER_MAC = "02:00:00:00:00:02"
BASE_TIME = 1_700_000_000.0


def build_svcb_rdata(priority, target, svc_params_bytes):
    """Build raw SVCB/HTTPS RDATA from components."""
    target_wire = b""
    if target == ".":
        target_wire = b"\x00"
    else:
        for label in target.rstrip(".").split("."):
            target_wire += bytes([len(label)]) + label.encode()
        target_wire += b"\x00"

    return struct.pack("!H", priority) + target_wire + svc_params_bytes


def build_svc_param(key, value):
    """Build a single SvcParam TLV."""
    return struct.pack("!HH", key, len(value)) + value


def build_alpn_value(protocols):
    """Build an ALPN SvcParam value. Each entry is either a string or a
    (string, length_override) tuple to inject a wrong length byte."""
    value = b""
    for proto in protocols:
        if isinstance(proto, tuple):
            encoded = proto[0].encode()
            value += bytes([proto[1]]) + encoded
        else:
            encoded = proto.encode()
            value += bytes([len(encoded)]) + encoded
    return value


def dns_query(qname, sport):
    return (
        Ether(src=CLIENT_MAC, dst=SERVER_MAC)
        / IP(src="10.0.0.2", dst="10.0.0.1")
        / UDP(sport=sport, dport=53)
        / DNS(
            id=0x1234,
            qr=0,
            qd=DNSQR(qname=qname, qtype=65),
        )
    )


def dns_response(qname, rdata, sport):
    return (
        Ether(src=SERVER_MAC, dst=CLIENT_MAC)
        / IP(src="10.0.0.1", dst="10.0.0.2")
        / UDP(sport=53, dport=sport)
        / DNS(
            id=0x1234,
            qr=1,
            qd=DNSQR(qname=qname, qtype=65),
            an=DNSRR(rrname=qname, type=65, ttl=300, rdata=rdata),
        )
    )


def connection(qname, sport, h3_length):
    """Return the query and response for one ALPN h2/h3 lookup."""
    alpn_value = build_alpn_value(["h2", ("h3", h3_length)])
    svc_params = build_svc_param(SVCB_KEY_ALPN, alpn_value)
    rdata = build_svcb_rdata(1, ".", svc_params)
    return [dns_query(qname, sport), dns_response(qname, rdata, sport)]


def main():
    qname = "example.com"

    packets = []
    # len-too-long: ALPN with h3 length overshot (8 instead of 2)
    packets += connection(qname, sport=1234, h3_length=8)
    # len-too-short: ALPN with h3 length undershot (1 instead of 2), leaves trailing byte
    packets += connection(qname, sport=1235, h3_length=1)

    for index, pkt in enumerate(packets):
        pkt.time = BASE_TIME + index * 0.001

    wrpcap(str(Path(__file__).with_suffix("")), packets)


if __name__ == "__main__":
    main()
