
#include "plugin/Plugin.h"

#include "RADIUS.h"

BRO_PLUGIN_BEGIN(Bro, RADIUS)
	BRO_PLUGIN_DESCRIPTION("RADIUS analyzer");
	BRO_PLUGIN_ANALYZER("RADIUS", RADIUS::RADIUS_Analyzer);
	BRO_PLUGIN_BIF_FILE(events);
BRO_PLUGIN_END
