// See the file "COPYING" in the main distribution directory for copyright.

//
// An opinionated cluster-layout.zeek generator for single node deployments
// where the Zeek workers do not have ports allocated.
//
// The cluster-layout.zeek content is produced on stdout or written to the
// path given to the -o flag.
//
// Usage: zeek-cluster-layout-generator -L <loggers> -P <proxies> -W <workers>
// -a <listen_address> -p <port> -m <metrics_port> [-o outfile]
//
#include <unistd.h>
#include <algorithm>
#include <cctype>
#include <cerrno>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iostream>
#include <ostream>
#include <regex>
#include <string>
#include <vector>

namespace {

int checked_strtoul(int opt, const char* v) {
    const char* expected_end = v + std::strlen(v);
    char* end;
    auto r = std::strtoul(v, &end, 10);
    if ( end != expected_end ) {
        std::fprintf(stderr, "invalid numeric value for %c: %s\n", opt, v);
        std::exit(1);
    }

    return r;
}

/**
 * Default is a small cluster for quick testing.
 */
struct ClusterLayoutOptions {
    int loggers = 1;
    int proxies = 1;
    std::string workers = "1";
    int port = 27760;
    std::string address = "127.0.0.1";
    int metrics_port = 9991;
    std::string metrics_address = "127.0.0.1";

    std::string NextPort() {
        auto result = std::to_string(port) + "/tcp";
        ++port;
        return result;
    }
    std::string NextMetricsPort() {
        auto result = std::to_string(metrics_port) + "/tcp";
        ++metrics_port;
        return result;
    }
};

class ClusterLayout {
public:
    ClusterLayout(ClusterLayoutOptions opts) {
        lines.emplace_back("# Auto-generated by zeek-cluster-layout-generator");
        lines.emplace_back("");
        lines.emplace_back("redef Cluster::manager_is_logger = " + std::string(opts.loggers > 0 ? "F" : "T") + ";");
        lines.emplace_back("");
        lines.emplace_back("redef Cluster::nodes += {");

        AddNode("manager", "MANAGER", opts.address, opts.NextMetricsPort(), opts.NextPort());

        for ( int i = 1; i <= opts.loggers; i++ )
            AddNode("logger-" + std::to_string(i), "LOGGER", opts.address, opts.NextMetricsPort(), opts.NextPort());

        for ( int i = 1; i <= opts.proxies; i++ )
            AddNode("proxy-" + std::to_string(i), "PROXY", opts.address, opts.NextMetricsPort(), opts.NextPort());

        AddWorkers(opts);

        lines.emplace_back("};");

        lines.emplace_back("");
        lines.emplace_back("@load base/frameworks/telemetry/options");
        lines.emplace_back("redef Telemetry::metrics_address = \"" + opts.metrics_address + "\";");
        lines.emplace_back("redef Telemetry::metrics_port = Cluster::local_node_metrics_port();");
    }

    void AddNode(const std::string& name, const std::string& type, const std::string& ip,
                 const std::string& metrics_port = "", const std::string& port = "") {
        auto s = "    [\"" + name + "\"] = [$node_type=Cluster::" + type + ", $ip=" + ip;

        if ( ! port.empty() )
            s += ", $p=" + port;

        if ( name != "manager" )
            s += ", $manager=\"manager\"";

        if ( ! metrics_port.empty() )
            s += ", $metrics_port=" + metrics_port;

        s += "],";
        lines.push_back(std::move(s));
    }

    /**
     * Workers is either just the number of workers, or a "tag1:worker1 tag2:workers2 tag3:workers3"
     * that allows to have worker-{tag}-{index} style names.
     */
    void AddWorkers(ClusterLayoutOptions& opts) {
        if ( std::ranges::all_of(opts.workers.begin(), opts.workers.end(), [](auto c) { return std::isdigit(c); }) ) {
            int workers = checked_strtoul('W', opts.workers.c_str());
            for ( int i = 1; i <= workers; i++ )
                AddNode("worker-" + std::to_string(i), "WORKER", opts.address, opts.NextMetricsPort());
        }
        else {
            // Iterate through the eth1:8,eth2:32,eth3:4 range
            // of interface tag followed by number of workers and
            // add workers for each of them.
            std::string workers_optarg = opts.workers;

            // Allow comma or space separated list.
            std::replace(workers_optarg.begin(), workers_optarg.end(), ',', ' ');

            std::cmatch cmatch;
            std::regex re_tag_workers("\\s*([-_0-9a-z]+):([0-9]+)\\s*");
            const char* p = workers_optarg.c_str();
            while ( std::regex_search(p, cmatch, re_tag_workers) ) {
                std::string tag = cmatch[1].str();
                std::string nstr = cmatch[2].str();
                int n = checked_strtoul('W', nstr.c_str());

                for ( int i = 1; i <= n; i++ )
                    AddNode("worker-" + tag + "-" + std::to_string(i), "WORKER", opts.address, opts.NextMetricsPort());

                p += cmatch.length();
            }

            if ( *p ) {
                std::fprintf(stderr, "-W invalid: '%s'\n", opts.workers.c_str());
                std::exit(1);
            }
        }
    }

    void Print(std::ostream& out) {
        for ( const auto& l : lines )
            out << l << "\n";
    }

private:
    std::vector<std::string> lines;
};

void usage(const char* prog) {
    fprintf(stdout,
            "Usage: %s -L <loggers> -P <proxies> -W <workers> -a <address> -p <port> -m <metrics_port>"
            "-b <metrics_address> [-o <outfile>]\n",
            prog);
}

} // namespace

int main(int argc, char* argv[]) {
    ClusterLayoutOptions opts;

    std::string out = "-";
    opterr = 0;

    while ( int c = getopt(argc, argv, "hL:P:W:a:p:m:b:o:") ) {
        if ( c < 0 )
            break;

        switch ( c ) {
            case 'L': opts.loggers = checked_strtoul(c, optarg); break;
            case 'P': opts.proxies = checked_strtoul(c, optarg); break;
            case 'W': opts.workers = optarg; break;
            case 'a': opts.address = optarg; break;
            case 'p': opts.port = checked_strtoul(c, optarg); break;
            case 'm': opts.metrics_port = checked_strtoul(c, optarg); break;
            case 'b': opts.metrics_address = optarg; break;
            case 'o': out = optarg; break;
            case 'h': usage(argv[0]); std::exit(0);
            case '?': std::fprintf(stderr, "unrecognized flag %c\n", optopt); std::exit(1);
        }
    }

    ClusterLayout layout(std::move(opts));

    // stdout print?
    if ( out == "-" ) {
        layout.Print(std::cout);
        return 0;
    }

    std::ofstream os(out, std::ios::trunc);
    if ( ! os.is_open() ) {
        std::fprintf(stderr, "failed to open %s: %s\n", out.c_str(), std::strerror(errno));
        std::exit(1);
    }

    layout.Print(os);
    return 0;
}
