### BTest baseline data generated by btest-diff. Do not edit. Use "btest -U/-u" to update. Requires BTest >= 0.63.
# Auto-generated by zeek-cluster-layout-generator

redef Cluster::manager_is_logger = F;

redef Cluster::nodes += {
    ["manager"] = [$node_type=Cluster::MANAGER, $ip=127.0.2.1, $p=20000/tcp, $metrics_port=30000/tcp],
    ["logger-1"] = [$node_type=Cluster::LOGGER, $ip=127.0.2.1, $p=20001/tcp, $manager="manager", $metrics_port=30001/tcp],
    ["logger-2"] = [$node_type=Cluster::LOGGER, $ip=127.0.2.1, $p=20002/tcp, $manager="manager", $metrics_port=30002/tcp],
    ["logger-3"] = [$node_type=Cluster::LOGGER, $ip=127.0.2.1, $p=20003/tcp, $manager="manager", $metrics_port=30003/tcp],
    ["proxy-1"] = [$node_type=Cluster::PROXY, $ip=127.0.2.1, $p=20004/tcp, $manager="manager", $metrics_port=30004/tcp],
    ["proxy-2"] = [$node_type=Cluster::PROXY, $ip=127.0.2.1, $p=20005/tcp, $manager="manager", $metrics_port=30005/tcp],
    ["proxy-3"] = [$node_type=Cluster::PROXY, $ip=127.0.2.1, $p=20006/tcp, $manager="manager", $metrics_port=30006/tcp],
    ["proxy-4"] = [$node_type=Cluster::PROXY, $ip=127.0.2.1, $p=20007/tcp, $manager="manager", $metrics_port=30007/tcp],
    ["proxy-5"] = [$node_type=Cluster::PROXY, $ip=127.0.2.1, $p=20008/tcp, $manager="manager", $metrics_port=30008/tcp],
    ["worker-1"] = [$node_type=Cluster::WORKER, $ip=127.0.2.1, $manager="manager", $metrics_port=30009/tcp],
    ["worker-2"] = [$node_type=Cluster::WORKER, $ip=127.0.2.1, $manager="manager", $metrics_port=30010/tcp],
    ["worker-3"] = [$node_type=Cluster::WORKER, $ip=127.0.2.1, $manager="manager", $metrics_port=30011/tcp],
    ["worker-4"] = [$node_type=Cluster::WORKER, $ip=127.0.2.1, $manager="manager", $metrics_port=30012/tcp],
    ["worker-5"] = [$node_type=Cluster::WORKER, $ip=127.0.2.1, $manager="manager", $metrics_port=30013/tcp],
    ["worker-6"] = [$node_type=Cluster::WORKER, $ip=127.0.2.1, $manager="manager", $metrics_port=30014/tcp],
    ["worker-7"] = [$node_type=Cluster::WORKER, $ip=127.0.2.1, $manager="manager", $metrics_port=30015/tcp],
};

@load base/frameworks/telemetry/options
redef Telemetry::metrics_address = "10.0.0.1";
redef Telemetry::metrics_port = Cluster::local_node_metrics_port();
