### BTest baseline data generated by btest-diff. Do not edit. Use "btest -U/-u" to update. Requires BTest >= 0.63.
# Auto-generated by zeek-cluster-layout-generator

redef Cluster::nodes += {
    ["manager"] = [$node_type=Cluster::MANAGER, $ip=127.0.2.1, $p=27760/tcp, $metrics_port=9991/tcp],
    ["logger-1"] = [$node_type=Cluster::LOGGER, $ip=127.0.2.1, $p=27761/tcp, $manager="manager", $metrics_port=9992/tcp],
    ["logger-2"] = [$node_type=Cluster::LOGGER, $ip=127.0.2.1, $p=27762/tcp, $manager="manager", $metrics_port=9993/tcp],
    ["logger-3"] = [$node_type=Cluster::LOGGER, $ip=127.0.2.1, $p=27763/tcp, $manager="manager", $metrics_port=9994/tcp],
    ["proxy-1"] = [$node_type=Cluster::PROXY, $ip=127.0.2.1, $p=27764/tcp, $manager="manager", $metrics_port=9995/tcp],
    ["proxy-2"] = [$node_type=Cluster::PROXY, $ip=127.0.2.1, $p=27765/tcp, $manager="manager", $metrics_port=9996/tcp],
    ["proxy-3"] = [$node_type=Cluster::PROXY, $ip=127.0.2.1, $p=27766/tcp, $manager="manager", $metrics_port=9997/tcp],
    ["proxy-4"] = [$node_type=Cluster::PROXY, $ip=127.0.2.1, $p=27767/tcp, $manager="manager", $metrics_port=9998/tcp],
    ["proxy-5"] = [$node_type=Cluster::PROXY, $ip=127.0.2.1, $p=27768/tcp, $manager="manager", $metrics_port=9999/tcp],
    ["worker-1-1"] = [$node_type=Cluster::WORKER, $ip=127.0.2.1, $manager="manager", $metrics_port=10000/tcp],
    ["worker-1-2"] = [$node_type=Cluster::WORKER, $ip=127.0.2.1, $manager="manager", $metrics_port=10001/tcp],
    ["worker-2-1"] = [$node_type=Cluster::WORKER, $ip=127.0.2.1, $manager="manager", $metrics_port=10002/tcp],
    ["worker-2-2"] = [$node_type=Cluster::WORKER, $ip=127.0.2.1, $manager="manager", $metrics_port=10003/tcp],
};

redef Cluster::manager_is_logger = F;

@load base/frameworks/telemetry/options

# Either use ZEEK_TELEMETRY_LISTEN_ADDRESS env or the value from node$ip.
const metrics_address_env = getenv("ZEEK_TELEMETRY_LISTEN_ADDRESS");
@if ( |metrics_address_env| > 0 )
redef Telemetry::metrics_address = metrics_address_env;
@else
@if ( Cluster::node in Cluster::nodes )
const my_ip = Cluster::nodes[Cluster::node]$ip;
const my_ip_str = is_v4_addr(my_ip) ? cat(my_ip) : cat("[", my_ip, "]");
redef Telemetry::metrics_address = my_ip_str;
@endif
@endif

# Always use the metrics port from the cluster layout for now
# This can/may change in the future!
redef Telemetry::metrics_port = Cluster::local_node_metrics_port();
