### BTest baseline data generated by btest-diff. Do not edit. Use "btest -U/-u" to update. Requires BTest >= 0.63.
# Auto-generated by zeek-cluster-layout-generator

module Cluster;

type Host: record {
	ip: addr;
};

const hosts: table[string] of Host &redef;

redef Cluster::hosts += {
	["mgr"] = [$ip=[2001:400:211::121]],
	["wkr-1"] = [$ip=[2001:400:211::122]],
	["wkr-2"] = [$ip=[2001:400:211::123]],
};

redef Cluster::nodes += {
    ["manager"] = [$node_type=Cluster::MANAGER, $ip=hosts["mgr"]$ip, $p=27760/tcp, $metrics_port=9991/tcp],
    ["mgr-logger-1"] = [$node_type=Cluster::LOGGER, $ip=hosts["mgr"]$ip, $p=27761/tcp, $manager="manager", $metrics_port=9992/tcp],
    ["mgr-proxy-1"] = [$node_type=Cluster::PROXY, $ip=hosts["mgr"]$ip, $p=27762/tcp, $manager="manager", $metrics_port=9993/tcp],
    ["mgr-proxy-2"] = [$node_type=Cluster::PROXY, $ip=hosts["mgr"]$ip, $p=27763/tcp, $manager="manager", $metrics_port=9994/tcp],
    ["wkr-1-worker-eth0-1"] = [$node_type=Cluster::WORKER, $ip=hosts["wkr-1"]$ip, $manager="manager", $metrics_port=9991/tcp],
    ["wkr-1-worker-eth0-2"] = [$node_type=Cluster::WORKER, $ip=hosts["wkr-1"]$ip, $manager="manager", $metrics_port=9992/tcp],
    ["wkr-1-worker-eth0-3"] = [$node_type=Cluster::WORKER, $ip=hosts["wkr-1"]$ip, $manager="manager", $metrics_port=9993/tcp],
    ["wkr-1-worker-eth0-4"] = [$node_type=Cluster::WORKER, $ip=hosts["wkr-1"]$ip, $manager="manager", $metrics_port=9994/tcp],
    ["wkr-2-worker-eth0-1"] = [$node_type=Cluster::WORKER, $ip=hosts["wkr-2"]$ip, $manager="manager", $metrics_port=9991/tcp],
    ["wkr-2-worker-eth0-2"] = [$node_type=Cluster::WORKER, $ip=hosts["wkr-2"]$ip, $manager="manager", $metrics_port=9992/tcp],
    ["wkr-2-worker-eth0-3"] = [$node_type=Cluster::WORKER, $ip=hosts["wkr-2"]$ip, $manager="manager", $metrics_port=9993/tcp],
    ["wkr-2-worker-eth0-4"] = [$node_type=Cluster::WORKER, $ip=hosts["wkr-2"]$ip, $manager="manager", $metrics_port=9994/tcp],
    ["wkr-2-worker-eth1-1"] = [$node_type=Cluster::WORKER, $ip=hosts["wkr-2"]$ip, $manager="manager", $metrics_port=9995/tcp],
    ["wkr-2-worker-eth1-2"] = [$node_type=Cluster::WORKER, $ip=hosts["wkr-2"]$ip, $manager="manager", $metrics_port=9996/tcp],
    ["wkr-2-worker-eth1-3"] = [$node_type=Cluster::WORKER, $ip=hosts["wkr-2"]$ip, $manager="manager", $metrics_port=9997/tcp],
    ["wkr-2-worker-eth1-4"] = [$node_type=Cluster::WORKER, $ip=hosts["wkr-2"]$ip, $manager="manager", $metrics_port=9998/tcp],
};

redef Cluster::manager_is_logger = F;

@load base/frameworks/telemetry/options

# Either use ZEEK_TELEMETRY_LISTEN_ADDRESS env or the value from node$ip.
const metrics_address_env = getenv("ZEEK_TELEMETRY_LISTEN_ADDRESS");
@if ( |metrics_address_env| > 0 )
redef Telemetry::metrics_address = metrics_address_env;
@else
@if ( Cluster::node in Cluster::nodes )
const my_ip = Cluster::nodes[Cluster::node]$ip;
const my_ip_str = is_v4_addr(my_ip) ? cat(my_ip) : cat("[", my_ip, "]");
redef Telemetry::metrics_address = my_ip_str;
@endif
@endif

# Always use the metrics port from the cluster layout for now
# This can/may change in the future!
redef Telemetry::metrics_port = Cluster::local_node_metrics_port();
