#include "plugin/Plugin.h"

#include "Hash.h"

BRO_PLUGIN_BEGIN(Bro, FileHash)
	BRO_PLUGIN_DESCRIPTION("Hash file content");
	BRO_PLUGIN_FILE_ANALYZER("MD5", MD5);
	BRO_PLUGIN_FILE_ANALYZER("SHA1", SHA1);
	BRO_PLUGIN_FILE_ANALYZER("SHA256", SHA256);
	BRO_PLUGIN_BIF_FILE(events);
BRO_PLUGIN_END
